export const FETCH_APARTMENT = "FETCH_APARTMENT"
export const FETCH_LOADING = 'FETCH_LOADING'
export const CHANGE_STATUS_APARTMENT = 'CHANGE_STATUS_APARTMENT'
export const EDIT_APARTMENT = 'EDIT_APARTMENT'
export const SEARCH_APARTMENT = 'SEARCH_APARTMENT'
export const BAN_APARTMENT = "BAN_APARTMENT"
export const THUE_APARTMENT = "THUE_APARTMENT"
export const DELETE_APARTMENT = 'DELETE_APARTMENT'

export const LOADING = 'LOADING'

