export const FETCH_APARTMENT = "FETCH_APARTMENT";
export const FETCH_LOADING = "FETCH_LOADING";
export const CHANGE_STATUS_APARTMENT = "CHANGE_STATUS_APARTMENT";
export const EDIT_APARTMENT = "EDIT_APARTMENT";
export const SEARCH_APARTMENT = "SEARCH_APARTMENT";
export const BAN_APARTMENT = "BAN_APARTMENT";
export const THUE_APARTMENT = "THUE_APARTMENT";
export const DELETE_APARTMENT = "DELETE_APARTMENT";
export const FETCH_REQUEST_APARTMENT = "FETCH_REQUEST_APARTMENT";
export const FETCH_APPROVE_APARTMENT = "FETCH_APPROVE_APARTMENT";
export const REQUEST_APARTMENT = "REQUEST_APARTMENT";
export const APPROVE_APARTMENT = "APPROVE_APARTMENT";
export const DELETE_REQUEST_APPROVE = "DELETE_REQUEST_APPROVE";
export const CREATE_APARTMENT = "CREATE_APARTMENT"
export const EXPORT_EXCEL_APARTMENT = "EXPORT_EXCEL_APARTMENT"
export const SET_SELECTED_ROWS = "SET_SELECTED_ROWS"
export const CLEAR_SELECTED_ROWS = "CLEAR_SELECTED_ROWS"
export const EXPORT_EXCEL_SELECTED = "EXPORT_EXCEL_SELECTED"

//Customer
export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER'
export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER'

export const LOADING = "LOADING";
